import { auth, googleProvider } from "@/lib/firebase";
import { signInWithPopup, GoogleAuthProvider } from "firebase/auth";
import { Schedule, Goal } from "@/lib/store";

export interface CalendarEventData {
  summary: string;
  description: string;
  start: {
    dateTime: string;
    timeZone?: string;
  };
  end: {
    dateTime: string;
    timeZone?: string;
  };
}

export class CalendarService {
  /**
   * Requests Google Calendar access via Firebase popup.
   * Returns the OAuth Access Token.
   */
  static async requestCalendarAccess(): Promise<string> {
    const provider = new GoogleAuthProvider();
    provider.addScope("https://www.googleapis.com/auth/calendar.events");
    
    // Force prompt to ensure we get a new access token with the right scopes if needed
    provider.setCustomParameters({
      prompt: "consent",
    });

    try {
      const result = await signInWithPopup(auth, provider);
      const credential = GoogleAuthProvider.credentialFromResult(result);
      if (!credential || !credential.accessToken) {
        throw new Error("Failed to retrieve Google Access Token.");
      }
      return credential.accessToken;
    } catch (error: any) {
      console.error("Calendar access error:", error);
      throw new Error(error.message || "Failed to authenticate with Google Calendar.");
    }
  }

  /**
   * Creates a single event in the user's primary Google Calendar.
   */
  static async createEvent(accessToken: string, eventData: CalendarEventData): Promise<any> {
    const response = await fetch("https://www.googleapis.com/calendar/v3/calendars/primary/events", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(eventData),
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.error?.message || "Failed to create calendar event.");
    }

    return await response.json();
  }

  /**
   * Syncs an entire AI schedule to Google Calendar.
   */
  static async syncSchedule(accessToken: string, schedule: Schedule, goal: Goal): Promise<number> {
    let eventsCreated = 0;
    
    // We start scheduling from today. 
    // If the user's working window for today has already passed, ideally we'd start tomorrow,
    // but for simplicity, we'll map Day 1 -> Today, Day 2 -> Tomorrow, etc.
    let currentDate = new Date();
    
    for (const day of schedule.days) {
      for (const task of day.tasks) {
        // Parse start and end times from the task, or default to 09:00 - 10:00
        const startTimeStr = task.startTime || "09:00";
        const endTimeStr = task.endTime || "10:00";
        
        const [startHour, startMinute] = startTimeStr.split(":").map(Number);
        const [endHour, endMinute] = endTimeStr.split(":").map(Number);
        
        const eventStart = new Date(currentDate);
        eventStart.setHours(startHour || 9, startMinute || 0, 0, 0);
        
        const eventEnd = new Date(currentDate);
        eventEnd.setHours(endHour || (startHour ? startHour + task.hours : 10), endMinute || 0, 0, 0);

        const eventData: CalendarEventData = {
          summary: task.taskTitle,
          description: `Generated by FocusFlow AI\n\nGoal: ${goal.title}`,
          start: {
            dateTime: eventStart.toISOString(),
            timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
          },
          end: {
            dateTime: eventEnd.toISOString(),
            timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
          },
        };

        try {
          await this.createEvent(accessToken, eventData);
          eventsCreated++;
        } catch (e) {
          console.error("Failed to sync task:", task.taskTitle, e);
          // Continue trying to sync the rest
        }
      }
      
      // Increment the date for the next schedule day
      currentDate.setDate(currentDate.getDate() + 1);
    }
    
    return eventsCreated;
  }
}
